apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tdemo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tdemo
    # networking.knative.dev/visibility: cluster-local
  annotations:
    autoscaling.knative.dev/minScale: "1"
spec:
  source:
    git:
      url: https://github.com/tsalm-pivotal/tap-tanzu-java-web-app
      ref:
        branch: main
